version: '3.5'
services: 
    angular-service:
      container_name: foodwastesimulator
      build: .
      tty: true
      volumes: 
        - './:/opt/app' 
      ports: 
        - '4200:4200' 
      command: > 
        sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"
